//This is a configuration file to VIM editor.Setting parameters to make easy to use the VIM editor. 

set nu
syntax on 
set nocompatible
set encoding=utf-8
set showcmd
filetype plugin indent on
set tabstop=2 shiftwidth=2
set expandtab
set backspace=indent,eol,start
set hlsearch
set incsearch
set ignorecase
set smartcase
